In [1]:
import array as arr
arr_x = arr.array("d", [98.6, 22.35, 72.1])

In [3]:
arr_x[1]

22.35

In [4]:
import numpy as np

In [5]:
array1d = np.array([1, 2, 3, 4])
array1d

array([1, 2, 3, 4])

In [6]:
array2d = np.array([[0, 1, 2],[2, 3, 4]])
array2d

array([[0, 1, 2],
       [2, 3, 4]])

In [7]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [8]:
np.eye(N = 4, M = 3, k = -2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [9]:
# Creating an array with numbers from 2 to 12 spaced out at intervals of 3
np.arange(2, 13, 3)

array([ 2,  5,  8, 11])

In [10]:
np.linspace(start = 5, stop = 10, num = 20)

array([ 5.        ,  5.26315789,  5.52631579,  5.78947368,  6.05263158,
        6.31578947,  6.57894737,  6.84210526,  7.10526316,  7.36842105,
        7.63157895,  7.89473684,  8.15789474,  8.42105263,  8.68421053,
        8.94736842,  9.21052632,  9.47368421,  9.73684211, 10.        ])

In [11]:
np.random.rand(2, 4)

array([[0.27346627, 0.1827647 , 0.39269909, 0.27003355],
       [0.57492884, 0.80932365, 0.39724582, 0.05920101]])

In [16]:
patient = np.array([[[100, 65, 160],
[150, 82, 200],
[ 90, 55, 80],
[130, 73, 220],
[190, 80, 150]],
[[ 95, 68, 140],
[145, 80, 222],
[ 90, 62, 100],
[150, 92, 200],
[140, 60, 90]],
[[110, 72, 160],
[160, 95, 185],
[100, 80, 110],
[140, 92, 120],
[100, 55, 100]],
[[110, 72, 160],
[160, 95, 185],
[100, 80, 110],
[140, 92, 120],
[100, 55, 100]]])

In [17]:
print(f"dtype: {patient.dtype} \nshape: {patient.shape} \nndim: {patient.ndim} \nsize: {patient.size}")

dtype: int64 
shape: (4, 5, 3) 
ndim: 3 
size: 60


In [18]:
patient[1][2][0]

90

In [19]:
print(f"itemsize: {patient.itemsize} \nnbytes: {patient.nbytes} \nstrides: {patient.strides}")

itemsize: 8 
nbytes: 480 
strides: (120, 24, 8)


## Try some Linear Algebra

In [20]:
m1 = np.random.randn(5, 5)
m1_e = np.linalg.eig(m1)

In [22]:
def print_detail(x):
    print(f"dtype: {x.dtype} \nshape: {x.shape} \nndim: {x.ndim} \nsize: {x.size}")

In [27]:
print_detail(m1_e[1])

dtype: complex128 
shape: (5, 5) 
ndim: 2 
size: 25


In [26]:
with np.printoptions(precision=3, suppress=True):
    print(m1_e[1])

[[-0.447+0.j    -0.004+0.272j -0.004-0.272j  0.328+0.067j  0.328-0.067j]
 [ 0.136+0.j    -0.111+0.414j -0.111-0.414j  0.275+0.244j  0.275-0.244j]
 [ 0.056+0.j     0.011+0.43j   0.011-0.43j   0.3  -0.306j  0.3  +0.306j]
 [-0.404+0.j    -0.36 -0.366j -0.36 +0.366j  0.616+0.j     0.616-0.j   ]
 [ 0.785+0.j     0.543+0.j     0.543-0.j     0.385-0.202j  0.385+0.202j]]


In [28]:
a = np.array([[1, 2, 3], [5, 4, 2], [8, 9, 7]])
b = np.array([6, 19, 47])
res = np.linalg.solve(a, b)

In [29]:
res

array([-6.27272727, 15.81818182, -6.45454545])